## 1. Menambahkan library
 "numpy" berguna memudahkan kita melakukan perhitungan saintifik seperti matriks, aljabar, statistik, dan sebagainya.    
 "matpotlib.pyplot" berguna untuk memvisualisaikan data melalui grafik atau diagram      
 "pandas" berguna untuk memproses data, mulai pembersihan data, manipulasi data, hingga melakukan analisis data.

In [320]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#  2. Import dataset
Memuat dataset dan kemudian menampilkan data tersebut agar bisa diproses

In [321]:
data = pd.read_csv("exams.csv")
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [322]:
print(x)

[['female' 'group D' 'some college' ... 'completed' 59.0 70]
 ['male' 'group D' "associate's degree" ... 'none' 96.0 93]
 ['female' 'group D' 'some college' ... 'none' 57.0 76]
 ...
 ['female' 'group A' 'high school' ... 'completed' 67.0 86]
 ['male' 'group E' 'high school' ... 'none' 80.0 72]
 ['male' 'group D' 'high school' ... 'none' nan 47]]


In [323]:
print(y)

[ 78  87  77  63  86  54  80  58  73  77  69  49  76  70  52  43  41  81
  85  74  62  76  71  86  88  72  51  59  71  86  85  79  75  37  82  54
  75  72  87  78  48  77  72  67  54  65  90  68  56  80  74  84  84  72
  63  61  80  93  78  66  75  63  80  73  71  36  66  88  57  73  78  80
  33  59  52  46  89  59  74  57  81  95  42  76  89  91  68  85  60  58
  61  75  38  74  83  97  87  78  95  64  74  53  63  60  84  74  72  74
  56  77  83  73  89  63  78 100  88  68  52  93  79  81  75  67  80  88
  80  97  75  60  60  55  51  63  83  60  88  77  66  74  61  64  80  78
  60  81  72  71  82  80  67  52  80  51  81  74 100  79  80  76  78  47
  57  55  57  50  53  60  74  77  82  69  74  38  59  74  68  70  87  57
  67  86  87  70  73  94  85  44  78  80  69  87  55  53  66  54  86  59
  99  94  92  57  67  85  77  94  53  67  58  59  56  57  73  88  77  90
  70  58  82  57  80  68  93  70  68  49  88  57  15  76  58  83  90  76
  72  82  93  66  77  47  72  70  73  81  80  72  6

# 3. Menampilkan atribut yang memiliki missing values
Menampilkan atribut yang memiliki missing values di dalamnya agar kita dapat mengetahui atribut mana yang perlu kita perbaiki.


In [324]:
data.isnull().sum()

gender                         23
race/ethnicity                  0
parental level of education     0
lunch                           8
test preparation course         0
math score                      4
reading score                   0
writing score                   0
dtype: int64

# 4. Memperbaiki Missing Value (nan)

# 4.1 Pembersihan Data Non-Numerik
Metode yang saya gunakan untuk memperbaiki missing values pada data non-Numerik tersebut yaitu dengan metode imputasi most frequent atau modus. metode ini akan mengambil data yang muncul paling banyak pada dataset. Jika diilustrasikan, terdapat 3 buah data X,Y,Z dan jika yang paling banyak muncul adalah data Z maka data Z yang akan diimputasikan pada Missing Values.

Langkah pertama yaitu kita harus mencari most_frequent data dari atribut yang memiliki missing values

In [325]:
most_frequent_gender = data["gender"].mode()[0]

In [326]:
print (most_frequent_gender)

male


In [327]:
most_frequent_lunch = data["lunch"].mode()[0]

In [328]:
print (most_frequent_lunch)

standard


Langkah Kedua, imputasikan data yang dihasilkan dari langkah pertama

In [329]:
data["gender"] = data["gender"].fillna(most_frequent_gender)

In [330]:
data.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          8
test preparation course        0
math score                     4
reading score                  0
writing score                  0
dtype: int64

In [331]:
data["lunch"] = data["lunch"].fillna(most_frequent_lunch)

In [332]:
data.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     4
reading score                  0
writing score                  0
dtype: int64

# 4.2 Pembersihan Data Numerik
Proses pembersihan data  pada data yang bersifat numerik, saya menggunakan metode imputasi dengan mean. Metode ini akan mengambil data dari rata-rata(mean) dari data pada atribut yang memiliki missing values yang mana nantinya akan diimputasikan pada data yang kosong pada atribut tersebut.

In [333]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
data['math score'] = imputer.fit_transform(data[['math score']])

In [334]:
print(data)

     gender race/ethnicity parental level of education         lunch  \
0    female        group D                some college      standard   
1      male        group D          associate's degree      standard   
2    female        group D                some college  free/reduced   
3      male        group B                some college  free/reduced   
4      male        group D          associate's degree      standard   
..      ...            ...                         ...           ...   
995    male        group C                some college      standard   
996    male        group C                some college      standard   
997  female        group A                 high school      standard   
998    male        group E                 high school      standard   
999    male        group D                 high school      standard   

    test preparation course  math score  reading score  writing score  
0                 completed   59.000000             70         

In [335]:
data.isnull().sum() 

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

# 5. Encoding data kategori (Atribut)
Proses encoding berguna untuk mengubah nilai kategori atau string menjadi nilai numerik agar dapat digunakan dalam analisis data atau model machine learning. 
Pada kasus ini saya menggunakan teknik encoding One-Hot-Encoding yang mana berjalan dengan membuat variabel dummy baru untuk setiap nilai kategori unik dan mengisinya dengan 0 atau 1.

In [336]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [337]:
print(x)

[[0.0 1.0 0.0 ... 'completed' 59.0 70]
 [0.0 0.0 1.0 ... 'none' 96.0 93]
 [0.0 1.0 0.0 ... 'none' 57.0 76]
 ...
 [0.0 1.0 0.0 ... 'completed' 67.0 86]
 [0.0 0.0 1.0 ... 'none' 80.0 72]
 [0.0 0.0 1.0 ... 'none' nan 47]]


# 6. Encoding data kategori (Class / Label) 
Pada bagian ini saya menggunakan teknik encoding LabelEncoder yang mana merupakan salah satu class yang dimiliki oleh library sklearn.preprocessing

In [338]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [339]:
print (y)

[51 60 50 36 59 27 53 31 46 50 42 22 49 43 25 16 14 54 58 47 35 49 44 59
 61 45 24 32 44 59 58 52 48 11 55 27 48 45 60 51 21 50 45 40 27 38 63 41
 29 53 47 57 57 45 36 34 53 66 51 39 48 36 53 46 44 10 39 61 30 46 51 53
  8 32 25 19 62 32 47 30 54 68 15 49 62 64 41 58 33 31 34 48 12 47 56 70
 60 51 68 37 47 26 36 33 57 47 45 47 29 50 56 46 62 36 51 73 61 41 25 66
 52 54 48 40 53 61 53 70 48 33 33 28 24 36 56 33 61 50 39 47 34 37 53 51
 33 54 45 44 55 53 40 25 53 24 54 47 73 52 53 49 51 20 30 28 30 23 26 33
 47 50 55 42 47 12 32 47 41 43 60 30 40 59 60 43 46 67 58 17 51 53 42 60
 28 26 39 27 59 32 72 67 65 30 40 58 50 67 26 40 31 32 29 30 46 61 50 63
 43 31 55 30 53 41 66 43 41 22 61 30  0 49 31 56 63 49 45 55 66 39 50 20
 45 43 46 54 53 45 39 46 58 34 46 41 28 45 10 46 26 39 54 45 14 41 17 33
 56 39 52 48 36 29 57 35 48 50 38 32 11 59 10 51 51 24 36 39 40 44 42 17
 45 45 16 15 73 27 29 24 23 20 20 47 48 53 72 56 34 47 27 43 55 27 51 19
 66 46 25 53 36 13 33 17 35 28 35 71 14 43 28 21 40

# 7. Membagi dataset ke dalam training set dan test set

In [340]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [341]:
print(x_train)

[[0.0 1.0 0.0 ... 'none' 72.0 85]
 [0.0 1.0 0.0 ... 'none' 82.0 97]
 [0.0 0.0 1.0 ... 'none' 28.0 27]
 ...
 [0.0 0.0 1.0 ... 'none' 79.0 72]
 [0.0 1.0 0.0 ... 'none' 78.0 78]
 [0.0 0.0 1.0 ... 'completed' 68.0 66]]


In [342]:
print(x_test)

[[0.0 0.0 1.0 ... 'none' 49.0 49]
 [0.0 0.0 1.0 ... 'completed' 72.0 73]
 [0.0 1.0 0.0 ... 'none' 38.0 45]
 ...
 [0.0 0.0 1.0 ... 'none' 55.0 50]
 [0.0 0.0 1.0 ... 'completed' 59.0 68]
 [0.0 0.0 1.0 ... 'none' 74.0 67]]


In [343]:
print(y_train)

[54 63  2 41 43 68 47 50 60 54 24 27 73 44 49 34 49 43 29 48 27 49 53 47
 23 55 47 71 18 47 37 46 14 25 55 48 48 67 59 49 37 64 35 61 26 37 43 35
 33 31 20 51 36 25 39 20 38 28 61 73 54 18 17 14 27 37 34 31 36 45 60 59
 43 46 57 54 35 45 66 72 52 29 25 55 70 39 25 56 61 40 35 67 42 43 73 54
 39 36 42 37 42 50 40 26 53 49 56 56 37 43 43 66 36 53 48 56 15 63 59 40
 51 41 49 51 51 36 34 39 43 35 20 66 54 29 30 39 45 39 20 19 44 69 40 32
 51 46 35 20 53 24 12 51 36 51 62 53 59 24 12 49 51 45 39 31 51 21 31 28
 52 30 37 48 47 37 61 25 30 34 47 40 32 11 51 25 48 25 35 15 43 33 36 33
 33 55 50 47 40 33 35 32 33 38 28 24 44 36 48 22 50 56 34 16 44 47 39 49
 48 33 22 52 22 58 12 39 46 61 47 52 45 38 60 44 54 47 51 22 61 63 52 43
 70 41 44 30 37 34 36 53 50 51 37 46 24 37 48 15 33 19 49 59 51 25  3 44
 59 36 62 51 52 28 45 41 61 72 39 56 30 57 18 36 53 62 45 48 41 62 23 40
 54 30 30 22 51 47 45 71 50 49 52 58 63 30 32 11 17 47 27 60 68 27 32 57
 34 50 37 45 58 27 48 73 60 17 34 30 61 53 59 21 47

In [344]:
print(y_test)

[16 48 17 16 46 26 17 45 33 53 24 53 31 26 42 36 57 53 57 60 39 73 35 19
 16 66 29 54 43 25 64 21 57 27 56 38 47 47 38 34 38 28 34 26 56 17 69 50
 32 44 50 55 49 27 55 51 32 45 67 41 43 50 60 59 34 69 46 32 51 54 32 28
 43 47 44 10 60 22 36 39 46 40 51 62 61 40 28 31 47 63 39 53 24 49 24 51
 38 69 54 54 35 43 40 73 41 27 48 19 66 23 38 40 65 39 51 47 24 30 52 35
 40 19 36 39  8 43 19 34 49 42 24 58 57 50 59 48 38 73 52 28 32 41 33 26
 46 38 30 42 48 13 45 28 46 32 53 43 43 66 62  0 49 67 61 29 35 36 53 54
 67 27 40 68 46 52 48 30 58 54 32 19 43 47 51 44 57 25 65 43 25 52 21 18
 49 42 72 58 39 20 39 40]


# 8. Feature Scaling

In [345]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
scaled_x_train = sc.fit_transform(x_train[:, :4])
scaled_x_test = sc.transform(x_test[:, :4])

In [346]:
print (scaled_x_train)

[[-0.06135239  1.05395348 -1.         -0.15171652]
 [-0.06135239  1.05395348 -1.         -0.15171652]
 [-0.06135239 -0.94880848  1.         -0.15171652]
 ...
 [-0.06135239 -0.94880848  1.         -0.15171652]
 [-0.06135239  1.05395348 -1.         -0.15171652]
 [-0.06135239 -0.94880848  1.         -0.15171652]]


In [347]:
print (scaled_x_test)

[[-0.06135239 -0.94880848  1.         -0.15171652]
 [-0.06135239 -0.94880848  1.         -0.15171652]
 [-0.06135239  1.05395348 -1.         -0.15171652]
 [-0.06135239  1.05395348 -1.         -0.15171652]
 [-0.06135239  1.05395348 -1.         -0.15171652]
 [-0.06135239 -0.94880848  1.         -0.15171652]
 [-0.06135239 -0.94880848  1.         -0.15171652]
 [-0.06135239  1.05395348 -1.         -0.15171652]
 [-0.06135239  1.05395348 -1.         -0.15171652]
 [-0.06135239 -0.94880848 -1.          6.59123998]
 [-0.06135239 -0.94880848  1.         -0.15171652]
 [-0.06135239 -0.94880848  1.         -0.15171652]
 [-0.06135239 -0.94880848  1.         -0.15171652]
 [-0.06135239 -0.94880848  1.         -0.15171652]
 [-0.06135239  1.05395348 -1.         -0.15171652]
 [-0.06135239 -0.94880848  1.         -0.15171652]
 [-0.06135239  1.05395348 -1.         -0.15171652]
 [-0.06135239 -0.94880848 -1.          6.59123998]
 [-0.06135239  1.05395348 -1.         -0.15171652]
 [-0.06135239  1.05395348 -1.  